excluded:
  - Pods
opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_imports
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message

disabled_rules:
  # - line_length
  # - file_length
  - force_cast
  - todo
  - identifier_name
  - type_name
  - private_outlet
  - file_header

line_length: 
  - 300 #warning
  - 500 #error
file_length: 
  - 1500 #warning
  - 2000 #error
number_separator:
  minimum_length: 5 